namespace: "geodata"
container: "jacobwhall/geodata-container"
persistentVolumeName: "sciclone"
volumeInternalMountpoint: "/sciclone"
prefect:
  apiURL: "YOUR_URL_HERE"
  apiKey: "YOUR_API_KEY_HERE"
  workQueue: "geodata"
